FLECS-Technologies/flecs-public

daemon/scripts/flecs-update-hosts.sh

Older versions of Docker do not list a container's hostname in its
network aliases. Therefore the update-hosts script should query
hostname and network aliases separately and combine then into
an array of unique hostnames

Daemon: Query hostname and aliases for host entries

---

daemon/pkg/debian/etc/systemd/system/flecs.service
updater/pkg/debian/etc/systemd/system/flecs-updater.service

The beta VM (as well as all more recent Debian versions) blocks
on shutdown, "waiting for containerd-shim". By making the webapp
optionally depend on containerd.service, this issue is solved
while maintaining compatibility with older Debian versions where
this service does not exist.

Services: Fix VM shutdown issue

---

daemon/modules/data_layer/src/private/data_layer_private.cpp

- Browsing data previously returned an invalid response when
no data was available in the Service Mesh
- Timestamps still contained Zenoh router IDs, which do not
look pretty in the WebApp

Data layer: Fix response for browsing

---

daemon/pkg/debian/DEBIAN/postinst

Do not fail installation (remain in half-conf) when Docker
network flecs already exists. This is not an error condition
and should not lead to any issues with the installed package.

Daemon: Installation bugfix

---

apps/CMakeLists.txt
apps/tech.flecs.service-mesh/CMakeLists.txt
apps/tech.flecs.service-mesh/Dockerfile
apps/tech.flecs.service-mesh/assets/entrypoint.sh

Official Zenoh images are for amd64 only. Therefore rebuild them
as tech.flecs.service-mesh for all supported architectures.

Service Mesh: Build cross-platform Docker image

---

daemon/CMakeLists.txt
daemon/app/CMakeLists.txt
daemon/app/app.h
daemon/app/src/app.cpp
daemon/app/test/test_app.cpp
daemon/modules/app_manager/CMakeLists.txt
daemon/modules/app_manager/src/private/app_install.cpp
daemon/modules/app_manager/src/private/app_manager_private.cpp
daemon/modules/app_manager/src/private/app_sideload.cpp
daemon/modules/app_manager/src/private/app_uninstall.cpp
daemon/modules/app_manager/src/private/instance_create.cpp
daemon/modules/app_manager/src/private/instance_delete.cpp
daemon/modules/app_manager/src/private/instance_details.cpp
daemon/modules/app_manager/src/private/instance_start.cpp

Currently, app sideloading requires an app manifest to be present
in the local filesystem. This means that each manifest has to be
written into a temporary file first, and then again copied to the
local manifest store. Besides possible security implications (i.e.
blindly writing any content to the local, temporary filesystem),
this produces avoidable overhead, especially when sideloading
from the WebApp.
This patch allows loading an app manifest directly from a string
instead, which gives the opportunity to validate an app manifest
YAML before writing it to disk.

daemon: allow loading app manifests from string

---

daemon/api/src/api.cpp
daemon/modules/app_manager/private/app_manager_private.h
daemon/modules/app_manager/src/app_manager.cpp
daemon/modules/app_manager/src/private/app_sideload.cpp

Extend the sideloading API to not only accept paths in the local
filesystem, but a manifest YAML as string as well.

daemon: provide API to sideload via manifest string

---

daemon/api/lib/test/test_api_lib.cpp
daemon/modules/app_manager/src/private/app_sideload.cpp

When storing the app manifest, the file handle was kept open, which
led to an error in do_install as it has not been written back to
disk yet. Close the file handle after write to fix this.

daemon: bugfix in sideloading + gtest

---

daemon/modules/app_manager/private/app_manager_private.h
daemon/modules/app_manager/src/private/app_manager_private.cpp
daemon/modules/app_manager/src/private/app_uninstall.cpp

On upgrading, installing newer versions of system apps might be
required. As removal of system apps was not possible in v1.0.0,
a new path is added to allow forcing the removal.

daemon: allow force-removal of system apps

---

apps/tech.flecs.mqtt-bridge/CMakeLists.txt
apps/tech.flecs.service-mesh/CMakeLists.txt
daemon/modules/app_manager/src/private/app_manager_private.cpp

Upon new releases, a new version of system apps may or may not
be available. For now, hard-code the most recent version until
a more generic solution is in place, such as querying the most
recent version from the marketplace or determining it from the
provided Docker images.

daemon: hard-code available system apps versions

---

daemon/modules/system/src/system.cpp

For some interface types (such as CAN interfaces),
ifa_addr might be NULL, resulting in a SIGSEGV when
blindly accessing it.

daemon: fix potential sigsegv network adapter query

---

daemon/modules/jobs/CMakeLists.txt
daemon/modules/jobs/impl/jobs_impl.h
daemon/modules/jobs/job_progress.h
daemon/modules/jobs/job_status.h
daemon/modules/jobs/jobs.h
daemon/modules/jobs/src/impl/jobs_impl.cpp
daemon/modules/jobs/src/job_progress.cpp
daemon/modules/jobs/src/job_status.cpp
daemon/modules/jobs/src/jobs.cpp

Asynchronous operations each track their progress in a job_progress structure. Through a centralized API a list of all jobs as well as the progress of a single job should be retrievable.
This commit implements said /jobs and /jobs/{id} routes and adds improvements to the underlying structures, such as defined start values and automatically setting/resetting some status flags in the progress structure.

daemon: implement GET methods of jobs API

---

daemon/common/CMakeLists.txt
daemon/common/app/CMakeLists.txt
daemon/common/app/app.h
daemon/common/app/src/app.cpp
daemon/common/app/test/CMakeLists.txt
daemon/common/db/CMakeLists.txt
daemon/common/deployment/CMakeLists.txt
daemon/common/deployment/deployment.h
daemon/common/deployment/src/deployment.cpp
daemon/common/deployment/src/deployment_docker.cpp
daemon/common/deployment/test/test_deployment.cpp
daemon/common/instance/CMakeLists.txt
daemon/common/instance/instance.h
daemon/common/instance/src/instance.cpp
daemon/modules/app_manager/src/private/app_export.cpp
daemon/modules/app_manager/src/private/app_manager_private.cpp
daemon/modules/app_manager/src/private/instance_create.cpp
daemon/modules/app_manager/src/private/instance_delete.cpp
daemon/modules/app_manager/src/private/instance_details.cpp
daemon/modules/app_manager/src/private/instance_export.cpp
daemon/modules/app_manager/src/private/instance_update.cpp
daemon/modules/apps/impl/apps_impl.h
daemon/modules/apps/src/impl/apps_impl.cpp
daemon/modules/manifests/CMakeLists.txt

With the new manifests module, apps and manifests are more loosely coupled, which should be reflected in the class hierarchy. An App no now longer inherits from manifest, but weakly references its according manifest in the manifests module itself

daemon: refactor app class

---

daemon/CMakeLists.txt
daemon/modules/instances/impl/instances_impl.h
daemon/modules/instances/instances.h
daemon/modules/instances/src/impl/instances_impl.cpp
daemon/modules/instances/src/instances.cpp

After splitting up app_manager into a manifests, an apps and an instances module, working old code has to be moved to each new module. This commit migrates app_manager code related to instance management to the new instances module.

daemon: migrate app_manager code to instances

---

daemon/common/deployment/src/deployment.cpp

In case an instance remains throughout uninstallation of an App (e.g. as instance deletion is unsuccessful or not performed due to shutdown ...), creating a new instance after reinstallation of this App should pick up the leftover instance and reactivate it. However, this currently leads to a crash as pointers are not checked in the according code path.
Instead of direct pointer access, use the safe interface provided by the instance, which returns a valid result even if the instance is currently orphaned.

daemon: fix potential crash if instance cleanup is unsucessful

---

util/archive/CMakeLists.txt
util/archive/archive.h
util/archive/impl/archive_entry.h
util/archive/impl/base_archive.h
util/archive/impl/base_common.h
util/archive/impl/read_archive.h
util/archive/impl/write_archive.h
util/archive/impl/write_base.h
util/archive/impl/write_disk.h
util/archive/src/archive.cpp
util/archive/src/impl/archive_entry.cpp
util/archive/src/impl/base_archive.cpp
util/archive/src/impl/base_common.cpp
util/archive/src/impl/read_archive.cpp
util/archive/src/impl/write_archive.cpp
util/archive/src/impl/write_base.cpp
util/archive/src/impl/write_disk.cpp
util/archive/test/CMakeLists.txt
util/archive/test/test_archive.cpp

Export/import requires creation and extraction of archives. This util provides a wrapper around libarchive, which is capable of handling .zip and .tar(.gz) files through single function calls.

util: provide compression/decompression interface

---

daemon/modules/instances/impl/instances_impl.h
daemon/modules/instances/instances.h
daemon/modules/instances/src/impl/instances_impl.cpp
daemon/modules/instances/src/instances.cpp
daemon/modules/jobs/job_progress.h
daemon/modules/jobs/src/impl/jobs_impl.cpp
daemon/modules/jobs/src/job_progress.cpp
daemon/modules/jobs/test/test_jobs.cpp

When calling interface functions from other modules, having only an http interface means additional overhead and non-intuitive use. Therefore the main interface is designed for use from within FLECS, while small wrapper functions provide http functionality on top.

instances: split interface into http and synchronous

---

.github/workflows/develop.workflow.yml
.github/workflows/pull-request.workflow.yml
.github/workflows/release.workflow.yml
daemon/modules/version/CMakeLists.txt

Git 2.35.2 introduced new security measures, which prohibit execution of git commands in a repository owned by another user. It is therefore no longer possible to generate the GIT_SHA appended to our software version. As a solution, detect the owner of the root .git directory und use sudo to run the GIT_SHA generation as this user.

build: run git version detection through sudo

---

daemon/common/deployment/deployment.h
daemon/common/deployment/src/deployment.cpp
daemon/modules/instances/src/impl/instances_impl.cpp

When uninstalling an App, instances of another version might be removed in the process. This is caused by some pre-app_key code, which used explicit version filters instead of partial app_key's for filtering.
Remove explicit version_filters and rely on partial app_key's instead.

deployment: fix removal of instances of other app versions upon uninstall

---

daemon/common/deployment/src/deployment.cpp

Upon moving Instances to a newer/older version of the App, a backup is created to ensure the user can go back to a previous version without loss of data.
Two issues exist with this backup: First, Backing up of config files is attempted to the wrong directory. Second, the backup directory is not created, leading to permanently failing backups.
Fix backup path and create it in the process.

deployment: fix backup of config files on up-/downgrade

---

daemon/modules/flecsport/src/flecsport.cpp
external/crow-1.0+5/include/crow/parser.h
external/out/amd64/include/crow/parser.h
external/out/arm64/include/crow/parser.h
external/out/armhf/include/crow/parser.h

crow does not seem to have any nice way to directly upload files to disk. For imports, however, this seems quite important as smaller devices may quickly run out of ram when imports ranging in the GB region are uploaded.
Hack something into their http parser as a - hopefully - temporary workaround. In the future, this should be discussed with the author(s) of crow and made into a nice feature, if possible.

flecsport: nasty hack to upload imports to disk instead of ram

---

daemon/modules/apps/impl/apps_impl.h
daemon/modules/apps/src/apps.cpp
daemon/modules/apps/src/impl/apps_impl.cpp

The WebApp needs additional information about installed Apps to display optional buttons conditionally. This information would be available through other APIs, though they require increased effort on the WebApp side. For now, we fall back to providing this information in the /apps route directly and focus on a better approach at a later time.

apps: add multiInstance and editor to App list

---

daemon/modules/flecsport/src/impl/flecsport_impl.cpp

flecsport does not support merging deployments and resolving conflicts in its first implementation. Therefore, blindly delete all existing Instances before importing from an archive. This covers the basic and most common use-case of cloning devices while keeping the implementation simple at this point.

flecsport: remove existing Instances before import

---

daemon/common/deployment/src/deployment.cpp
daemon/modules/flecsport/export_manifest.h
daemon/modules/flecsport/src/export_manifest.cpp
daemon/modules/flecsport/src/impl/flecsport_impl.cpp
daemon/modules/instances/impl/instances_impl.h
daemon/modules/instances/instances.h
daemon/modules/instances/src/impl/instances_impl.cpp
daemon/modules/instances/src/instances.cpp

Some additional information about Instances should be preserved when exporting and importing Instances. Among these are Instance names, IP addresses and their specific configuration. Therefore, export full Instances instead of only their metadata to restore their full representation on import.

flecsport: export/import all Instance details

---

daemon/modules/version/CMakeLists.txt

Building within flecs-build container is now possible as user, no more root privileges required. Therefore, running git revision detection does not need to run through sudo anymore.

build: no more sudo for reading git revision

---

daemon/modules/instances/src/impl/instances_impl.cpp

For async operations on Instances, only the instance_id is shown in the job description (such as "stopping instance xyz"). To provide more information to the user, also the App should be shown, in case the user wants to configure, remove, ... this specific Instance.
Change the relevant operations to display the App alongside the instance_id (such as "stopping instance xyz (App1 1.2.3.4-1)")

jobs: map instance_id to App in job descriptions

---

daemon/common/app/manifest/env_var/src/env_var.cpp
daemon/common/app/manifest/env_var/test/test_env_var.cpp
daemon/common/app/manifest/test/test_app_manifest.cpp

Dashes should have been allowed in the first place following FLX-333. Somehow they were forgotten, so here goes...

manifest: allow dashes in environment variable names

---

CMakeLists.txt
daemon/api/lib/test/CMakeLists.txt
daemon/api/test/CMakeLists.txt
daemon/common/app/manifest/conffile/test/CMakeLists.txt
daemon/common/app/manifest/env_var/test/CMakeLists.txt
daemon/common/app/manifest/port_range/test/CMakeLists.txt
daemon/common/app/manifest/startup_option/test/CMakeLists.txt
daemon/common/app/manifest/test/CMakeLists.txt
daemon/common/app/manifest/volume/test/CMakeLists.txt
daemon/common/deployment/test/CMakeLists.txt
daemon/common/network/test/CMakeLists.txt
daemon/modules/apps/test/CMakeLists.txt
daemon/modules/console/test/CMakeLists.txt
daemon/modules/device/test/CMakeLists.txt
daemon/modules/instances/test/CMakeLists.txt
daemon/modules/jobs/test/CMakeLists.txt
daemon/modules/manifests/test/CMakeLists.txt
daemon/modules/system/test/CMakeLists.txt
daemon/modules/version/test/CMakeLists.txt
util/archive/test/CMakeLists.txt
util/cxx23/test/CMakeLists.txt
util/datetime/test/CMakeLists.txt
util/network/test/CMakeLists.txt
util/process/test/CMakeLists.txt
util/random/test/CMakeLists.txt
util/signal_handler/test/CMakeLists.txt
util/string/test/CMakeLists.txt
util/sysfs/test/CMakeLists.txt
util/udev/test/CMakeLists.txt
util/usb/test/CMakeLists.txt

- Outsources target 'coverage'
- Fixes building of unit tests

Update submodule flecs-build

---

Cargo.lock
flecs-core/Cargo.toml
flecs-core/src/relic/device/usb.rs

use fallback if name or vendor is not present in db

Use crate usb-ids to read device names and vendors

---

flecs/common/network/src/network_type.cpp
flecs/common/network/test/test_network_type.cpp

- "ipvlan" is required for parsing output from `docker inspect`

network: fix from_string/to_string conversion

---

flecs-core/src/jeweler/gem/instance/docker/mod.rs

Log error if instance can not be restarted during export instead of returning the error

gem::instance::docker: Allow failing instance restart during export
