LICENSE-3RDPARTY, backend/CMakeLists.txt, build/cmake/docker.cmake, cli/CMakeLists.txt, daemon/CMakeLists.txt, daemon/modules/private/app_manager_private.h, daemon/src/app/app.cpp, daemon/src/lib/private/libflecs_private.cpp, daemon/src/modules/app_manager.cpp, daemon/src/modules/private/app_manager_private.cpp, daemon/src/signal_handler/signal_handler.cpp
- ensure only one instance of single-instance apps
- autostart apps after reboot
- various (un-)installation fixes
- minor fixes & improvements throughout all components
=> Bugfix session: part 3

backend/src/http_request_handler.cpp, daemon/app/app_status.h, daemon/daemon.h, daemon/instance/instance_status.h, daemon/modules/private/app_manager_private.h, daemon/src/daemon.cpp, daemon/src/main.cpp, daemon/src/modules/private/app_manager_private.cpp
- pass some more info to WebApp
- fix crashes on database inconsistency
- fix restarting instances after reboot
- fix hanging process on shutdown
- fix reporting of instance status
=> Bugfix session: part 4

mqtt/mqtt_client.h, mqtt/mqtt_errors.h
- make error codes independent of mosquitto (sort of)
- clang-format
=> mqtt: minor preparational changes for data-layer

daemon/modules/app_manager/src/private/app_uninstall.cpp, daemon/modules/app_manager/src/private/instance_stop.cpp
- empty response
- instances were not stopped
- instances remained as dead containers
=> Daemon: Bugfixes for app uninstallation

flunder/examples/flunder_client_example.cpp, flunder/src/private/flunder_client_private.cpp
- fix potential crash with new JSON library
- add more published data in C++ example
- add timestamps in C++ example
=> flunder: bugfixes and extended examples

flunder/examples/flunder_client_example.cpp
- print received values
- print time between send/receive
=> flunder: extend C++ example

daemon/common/app/app.h, daemon/common/app/manifest/network/network.h, daemon/common/deployment/deployment.h, daemon/common/deployment/deployment_docker.h, daemon/common/deployment/src/deployment.cpp, daemon/common/deployment/src/deployment_docker.cpp, daemon/common/deployment/test/test_deployment.cpp, daemon/common/instance/CMakeLists.txt, daemon/common/instance/instance.h, daemon/common/instance/src/instance.cpp, daemon/common/types/network_type.h, daemon/modules/app_manager/private/app_manager_private.h, daemon/modules/app_manager/src/private/app_install.cpp, daemon/modules/app_manager/src/private/app_list.cpp, daemon/modules/app_manager/src/private/app_manager_private.cpp, daemon/modules/app_manager/src/private/app_uninstall.cpp, daemon/modules/app_manager/src/private/instance_create.cpp, daemon/modules/app_manager/src/private/instance_delete.cpp, daemon/modules/app_manager/src/private/instance_details.cpp, daemon/modules/app_manager/src/private/instance_start.cpp, daemon/modules/app_manager/src/private/instance_stop.cpp
- make instances know their corresponding app
- improve test coverage
- move d-pointer functions to .cpp
=> daemon: refactoring

.vscode/c_cpp_properties.json, daemon/modules/system/src/system.cpp, daemon/modules/system/system.h, daemon/modules/system/test/test_system.cpp, daemon/modules/version/src/version.cpp, daemon/modules/version/test/test_version.cpp
- redirect to v2 api
- improve test coverage
=> daemon: refactor system module

.vscode/c_cpp_properties.json, daemon/modules/marketplace/marketplace.h, daemon/modules/marketplace/src/marketplace.cpp, daemon/modules/marketplace/test/CMakeLists.txt, daemon/modules/marketplace/test/test_marketplace.cpp, daemon/modules/system/system.h
- redirect to v2 api
- improve test coverage
=> daemon: refactor marketplace module

daemon/modules/data_layer/data_layer.h, daemon/modules/data_layer/private/data_layer_private.h, daemon/modules/data_layer/src/data_layer.cpp, daemon/modules/data_layer/src/private/data_layer_private.cpp
- redirect to v2 api
- unify function return types
=> daemon: refactor data_layer module

daemon/modules/apps/src/impl/apps_impl.cpp
Add progress information to uninstallation process, which is available through jobs API. Allow WebApp and other clients to display progress information to the user.
=> daemon: track progress of App uninstallation

daemon/common/deployment/src/deployment_docker.cpp
When running FLECS in a containerized context, mapping archives for extraction is not always a valid option to restore volumes. This is because extraction takes place in a new container context, which may have a different view on directories (namely /var/lib/flecs/imports). The safer approach is to copy the archives to the new container context to make sure they exist in the expected location.
=> flecsport: copy archive to volume-restore container

flecs/modules/deployments/src/types/deployment_docker.cpp, flecs/modules/deployments/test/CMakeLists.txt, flecs/modules/deployments/test/test_docker.cpp
- also fixes do_query_network returning incomplete data
=> docker: review and cleanup do_create_network function

flecs-core/src/lore/mod.rs, flecs-core/src/sorcerer/spell/manifest.rs
=> FLX-735 Send maximum supported app manifest version when getting manifest from console

Cargo.lock, examples/Cargo.toml, examples/princess_quest.rs, flecs-core/src/quest/mod.rs, flecs-core/src/quest/quest_master.rs
by providing Quest::create_sub_quest and Quest::spawn_sub_quest for subquest creation
=> quest: Improve usability 

flecs-core/src/jeweler/app.rs, flecs-core/src/jeweler/deployment.rs, flecs-core/src/jeweler/gem/app.rs, flecs-core/src/jeweler/gem/deployment/docker.rs, flecs-core/src/sorcerer/appraiser.rs, flecs-core/src/sorcerer/authmancer.rs, flecs-core/src/sorcerer/spell/auth.rs, flecs_core_cxx_bridge/src/token.rs
Pass new struct Token around, instead of separate username and password
=> Return empty option on no content response for token from console

flecs-core/src/fsm/server_impl.rs, flecs-core/src/jeweler/deployment.rs, flecs-core/src/jeweler/gem/deployment/docker.rs, flecs-core/src/jeweler/gem/instance/mod.rs, flecs-core/src/jeweler/instance.rs, flecs-core/src/sorcerer/instancius.rs, flecs-core/src/sorcerer/spell/instance.rs
gem::instance: Copy config from container on stop
=> FLX-854 instancius: Stop instance

flecs-core/src/fsm/server_impl/instances.rs, flecs-core/src/fsm/server_impl/mod.rs
=> server_impl: Validate instance id only once

CMakeLists.txt
fixes build with newer rustc versions
=> rust: Update corrision to v0.5.1

api/openapi.yaml, flecs-core/src/fsm/server_impl/api/v2/apps/app/mod.rs, flecs-core/src/fsm/server_impl/api/v2/apps/mod.rs, flecs-core/src/fsm/server_impl/api/v2/device/onboarding/mod.rs, flecs-core/src/fsm/server_impl/api/v2/instances/instance_id/mod.rs, flecs-core/src/fsm/server_impl/apps.rs, flecs-core/src/fsm/server_impl/device.rs, flecs-core/src/fsm/server_impl/instances.rs, flecsd_axum_server/README.md, flecsd_axum_server/src/apis/apps.rs, flecsd_axum_server/src/apis/device.rs, flecsd_axum_server/src/apis/instances.rs, flecsd_axum_server/src/server/mod.rs
GET /v2/apps
GET /v2/apps/{app}
DELETE /v2/apps/{app}
PATCH /v2/instances/{instance_id}
DELETE /v2/instances/{instance_id}
POST /v2/device/onboarding
=> api: Add 500 responses to api
